In [1]:
import numpy as np

In [2]:
#easiest way to create numpy ndarray
#arange is similar to python range('start','stop','end')
#reshape() method will convert to a matrix of tuple shape
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
#way to iterate through an array cell by cell
for cell in a.flatten():
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [16]:
#Quiz #1: create a letter array from 'a' to 'j' and
#display various properties: size, shape, dtype and type
letter_array = np.array(['a','b','c','d','e','f','g','h','i','j'])
print("Letter array: ", letter_array)
print("shape: ", letter_array.shape)
print("size: ", letter_array.size)
print("dtype: ", letter_array.dtype)
print(type(letter_array))

Letter array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
shape:  (10,)
size:  10
dtype:  <U1
<class 'numpy.ndarray'>


In [20]:
#create 'zero' matrix of certain size
x = np.zeros((5,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
#create matrix of a certain size with all 'ones'
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#create matrix of certain size with same constant value (3)
x = np.full((2,3), 3)
x

array([[3, 3, 3],
       [3, 3, 3]])

In [29]:
#identity matrix using np.eye
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#create matrix with diagonal of values using np.diag
y = np.diag([3,2,1,5])
y

array([[3, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 5]])

In [35]:
#use linspace if you want to create N number of elements
#between 'start' and 'stop' similar to 'arange'
y = np.linspace(3,30,20).reshape(10,2)
y

array([[ 3.        ,  4.42105263],
       [ 5.84210526,  7.26315789],
       [ 8.68421053, 10.10526316],
       [11.52631579, 12.94736842],
       [14.36842105, 15.78947368],
       [17.21052632, 18.63157895],
       [20.05263158, 21.47368421],
       [22.89473684, 24.31578947],
       [25.73684211, 27.15789474],
       [28.57894737, 30.        ]])

In [37]:
#np.random.random or np.random.randint to create nums
y = np.random.randint(1,10, size=(2,3))
y

array([[5, 5, 4],
       [4, 6, 3]])

In [48]:
#np.random.normal(mean, std dev, size=shape) creates 
#arrays with certain conditions/properties
x = np.random.normal(50,3, size =(5,3))
print('X = \n', x)
print()
print('mean:', x.mean())
print('max value:', x.max())
print('min value:', x.min())
print('X has', (x < 50).sum(), 'negative numbers')
print('X has', (x > 50).sum(), 'positive numbers')

X = 
 [[51.98156318 48.86040339 54.01472907]
 [49.27623742 51.60188702 52.14436053]
 [41.19551353 48.75197198 48.62278825]
 [46.17499353 51.68541629 49.59509473]
 [50.67066547 53.70756908 53.94922474]]

mean: 50.148827881014704
max value: 54.014729074384334
min value: 41.19551352943215
X has 7 negative numbers
X has 8 positive numbers


In [49]:
#Quiz #2: create 4 x 4 ndarray, even #s incl b/w 2 to 32
x = np.linspace(2,32,16).reshape(4,4)
x

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [52]:
#can access ndarrays similar to python lists:
x = np.array([1,2,3,4,5])
print(x[0])
print(x[-1])

1
5


In [54]:
print(x)
x[4] = 20
print(x)

[1 2 3 4 5]
[ 1  2  3  4 20]


In [57]:
#works similarly for rank 2 ndarrays
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
#choose as [row, column]
print(x[0,0])
print(x[1,2])
print(x[2,2])

0
5
8


In [62]:
#DELETE along axis (o for rows,1 for col) using np.delete
y = np.delete(x, [1], axis = 1)
y
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
#APPEND allows to add elements to an ndarray
a = np.append(x, [[9, 10, 11]], axis = 0)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
b = np.append(a, [[3],[5],[8],[11]], axis = 1)
b

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  5],
       [ 6,  7,  8,  8],
       [ 9, 10, 11, 11]])

In [74]:
#INSERT column (axis =1) in variable 'b', at column '1'
x = np.insert(b, 1, [1,4,7,10], axis=1)
x

array([[ 0,  1,  1,  2,  3],
       [ 3,  4,  4,  5,  5],
       [ 6,  7,  7,  8,  8],
       [ 9, 10, 10, 11, 11]])

In [73]:
x = np.insert(b, 1, [3,4,5,5], axis = 0)
x

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  5],
       [ 3,  4,  5,  5],
       [ 6,  7,  8,  8],
       [ 9, 10, 11, 11]])

In [82]:
#np.vstack(var 1, on var2) and np.hstack(var 1, on var 2)
#allows stacking vertically and horizontally if same dim.

x = np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [84]:
b

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  5],
       [ 6,  7,  8,  8],
       [ 9, 10, 11, 11]])

In [88]:
z = np.vstack((x,b)).reshape(4,8)
z

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [ 0,  1,  2,  3,  3,  4,  5,  5],
       [ 6,  7,  8,  8,  9, 10, 11, 11]])